### ISSUE TITLE
Eorror in caffe.Net initialiazation

### ISSUE THREAD

**Issue by wang5566** [MTlab/onnx2caffe#1]
When run the project I got the prototxt but got the 
`Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR`
in the line caffe.Net() initialization.
I create a script to write only one line for initialization and successed. Why?

**Comment by ForestWang** [comment]
i got the same problem

**Comment by wang5566** [comment]
@YukiNagato 
But I set cpu mode by caffe.set_mode_cpu() and got the same result. Should re-compile caffe with cpu mode ?

**Comment by YukiNagato** [comment]
@wang5566 Yes, but you only have to disable cudnn when compiling caffe.
