### ISSUE TITLE
How did you copy the params?

### ISSUE THREAD

**Issue by Flames60** [MTlab/onnx2caffe#11]
Sorry to bother you again~ After I converted the model to caffe, I tested it and the result is so low.
So I checked the code, and there are some questions there, for example, how did you copy the params in BN layer?
The code is that:
` def _convert_BatchNorm(node,graph,err):

    epsilon = node.attrs.get("epsilon", 1e-5)
    scale = node.input_tensors[node.inputs[1]]
    bias = node.input_tensors[node.inputs[2]]
    mean = node.input_tensors[node.inputs[3]]
    var = node.input_tensors[node.inputs[4]]
    node_name = node.name

    input_name = str(node.inputs[0])
    output_name = str(node.outputs[0])

    if input_name==output_name:
        inplace = True
    else:
        inplace = False

    bn_layer = myf("BatchNorm", node_name+"_bn",[input_name],[output_name],eps = epsilon, use_global_stats = True, in_place=inplace)
    scale_layer = myf("Scale", node_name, [output_name],[output_name],in_place=True,bias_term=True)

    graph.channel_dims[output_name] = graph.channel_dims[input_name]

    return bn_layer,scale_layer
`

And the "myf" is:
`       def __init__(self, type_name, layer_name, inputs,outputs, **params):

        self.type_name = type_name
        self.inputs = inputs
        self.outputs = outputs
        self.params = params
        self.layer_name = layer_name
        self.ntop = self.params.get('ntop', 1)
        # use del to make sure kwargs are not double-processed as layer params
        if 'ntop' in self.params:
            del self.params['ntop']
        self.in_place = self.params.get('in_place', False)
        if 'in_place' in self.params:
            del self.params['in_place']
`
I found that there is no any codes to copy the params, so how did you do that?

**Comment by Flames60** [comment]
I have this question because I think maybe the problem is the params in BN and scale layer are given inversely.

**Comment by YukiNagato** [comment]
you can see the code in https://github.com/MTlab/onnx2caffe/blob/master/onnx2caffe/_weightloader.py#L38-L48

**Comment by Flames60** [comment]
Thanks!
