### ISSUE TITLE
doesn't support Dilated Conv？

### ISSUE THREAD

**Issue by Shuai-Xie** [MTlab/onnx2caffe#16]
My encoder network need 2 streams：

- one use common conv to get shallow features;
- the other one use dilated conv to get deep features with high-resolution as shallow features.

However, 
- shallow one works fine get 1/8 features (60, 80)
- deep one works wrong get 1/8 features (61, 81)

Are there any solutions?

I'll be very appreciated.

Thanks, 美图.

**Comment by YukiNagato** [comment]
Dilated Conv is support.
目前比较常见的feature不一致错误通常是pooling导致的，你的deep分支里有pooling吗？如果没有，你是如何做下采样的？能否确认一下到底是哪一层出的问题？如果是卷积层导致的feature大小不一致，可否把那层卷积的参数（kernel, stride, padding, dilated,输入大小）发一下？
