### ISSUE TITLE
TypeError: ONNX node of type Pad is not supported.

### ISSUE THREAD

**Issue by HongdongZheng** [MTlab/onnx2caffe#2]
Traceback (most recent call last):
  File "convertCaffe.py", line 110, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 54, in convertToCaffe
    err.unsupported_op(node)
  File "E:\mishang\workspace\CE2P\onnx2caffe\onnx2caffe\_error_utils.py", line 36, in unsupported_op
    "ONNX node of type {} is not supported.\n".format(node.op_type,)
TypeError: ONNX node of type Pad is not supported.

**Comment by YukiNagato** [comment]
Hi, how did you get the onnx model? Is the model exported by pytorch? If so, what's your pytorch version?

**Comment by HongdongZheng** [comment]
Yes, the model was exported by pytorch.  Pytorch version: 0.4.1

**Comment by YukiNagato** [comment]
Could you try pytorch 0.4.0 instead? The "Pad" operator is new 0.4.1 and my code haven't support it yet.

**Comment by HongdongZheng** [comment]
I wil try, thanks

**Comment by HongdongZheng** [comment]
It's solved when change pytorch version to 0.4.0,  thanks a lot.
