### ISSUE TITLE
Error when converting

### ISSUE THREAD

**Issue by CaptainEven** [MTlab/onnx2caffe#3]
I1109 12:26:11.506861  7257 net.cpp:379] This network produces output 171
I1109 12:26:11.506953  7257 net.cpp:402] Top memory (TEST) required for data: 53798656 diff: 53798656
I1109 12:26:11.506961  7257 net.cpp:405] Bottom memory (TEST) required for data: 53796608 diff: 53796608
I1109 12:26:11.506968  7257 net.cpp:408] Shared (in-place) memory (TEST) by data: 10498560 diff: 10498560
I1109 12:26:11.506973  7257 net.cpp:411] Parameters memory (TEST) required for data: 48940960 diff: 48940960
I1109 12:26:11.506979  7257 net.cpp:414] Parameters shared memory (TEST) by data: 0 diff: 0
I1109 12:26:11.506984  7257 net.cpp:420] Network initialization done.
Traceback (most recent call last):
  File "convertCaffe.py", line 119, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 92, in convertToCaffe
    converter_fn(net, node, graph, err)
  File "/mnt/diskc/even/Car_DR/Onnx2caffe/onnx2caffe/_weightloader.py", line 89, in _convert_gemm
    net.params[node_name][0].data[...] = W
ValueError: could not broadcast input array from shape (512,512) into shape (512,2048)

Hi,
I have already exported onnx file of resnet18(last FC layer modified to 512, 512), how can i fix this problem?

**Comment by YukiNagato** [comment]
Hi, could you post the pytorch code of how you establish your resnet18 model?

**Comment by CaptainEven** [comment]
model = torchvision.models.resnet18(pretrained=True)
        # print(model)
        model.fc = nn.Linear(512, 512)

from torchvision.models, and only modify last fc:  (fc): Linear(in_features=512, out_features=1000, bias=True) to  (fc): Linear(in_features=512, out_features=512, bias=True)

**Comment by CaptainEven** [comment]
The whole structure is as follows:

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer2): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer3): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer4): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (avgpool): AvgPool2d(kernel_size=7, stride=1, padding=0)
  (fc): Linear(in_features=512, out_features=512, bias=True)
)

**Comment by CaptainEven** [comment]
I export onnx file like this:

from torch import Tensor
from models import *
import torch.onnx
import torchvision
import os
import sys


# input data
# dummy_input = torch.randn(1, 1, 128, 128)  # .cuda()
dummy_input = torch.randn(1, 3, 224, 224)

# 加载模型
# model_path = 'checkpoints/resnet18_9.pth'
model_path = 'checkpoints/resnet18_std_4.pth'
if not os.path.isfile(model_path):
    print('=> %s is invalid.' % model_path)
    sys.exit(-1)
else:
    print('=> %s is valid.' % model_path)

# model = resnet_face18(use_se=False)
model = torchvision.models.resnet18(pretrained=True)
model.fc = nn.Linear(512, 512)

model_state_dict = torch.load(model_path)
model.load_state_dict(model_state_dict)
print('=> model weights done.')

model = model  # .cuda()

torch.onnx.export(model, dummy_input, 'checkpoints/car_match.onnx', verbose=True)
print('=> export onnx done.')

**Comment by YukiNagato** [comment]
I believe it is caused by the difference of pooling between pytorch and caffe, as they use different "ceil mode" in pooling. In torchvision.models.resnet18, there is a module named "self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)". The input is a tensor with shape(1, 64, 112, 112) and the output will be (1, 64, 56, 56) in pytorch, but in caffe, the output will be (1, 64, 57, 57). 
My solution is changing this pooling module by adding a line:
model = torchvision.models.resnet18(pretrained=True)
**model.maxpool = nn.MaxPool2d(kernel_size=2, stride=2)**
model.fc = nn.Linear(512, 512)

**Comment by CaptainEven** [comment]
Thank you for your patient explanation and solution! I 'll have a try.

**Comment by CaptainEven** [comment]
The attempt failed the same as before. The same error message.

**Comment by CaptainEven** [comment]
I'm sorry for making a mistake when exporting oonx file(forget to modify maxpool  as train.py).  It worked!  I'll do more test now.

**Comment by amitjslearn2** [comment]
Is it resolved?
