### ISSUE TITLE
attribute is incorrectly named "radio" instead of "ratio".

### ISSUE THREAD

**Issue by trieck** [MTlab/onnx2caffe#6]
in the `_convert_dropout` function of _operators.py, the code reads:

`ratio = node.attrs.get('radio', 0.5)`

instead of the correct attribute "ratio":

`ratio = node.attrs.get('ratio', 0.5)`

**Comment by YukiNagato** [comment]
Sorry for the late reply because i were on holiday, it's fixed now. Thank you very much!
