### ISSUE TITLE
onnx2caffe支持将onnx格式目标检测SSD模型能转成caffe模型吗？

### ISSUE THREAD

**Issue by 1976277169** [MTlab/onnx2caffe#8]

**Comment by YukiNagato** [comment]
你好，能先把网络结构给我看一下吗，我试着转一下

**Comment by 1976277169** [comment]
> 
> 
> 你好，能先把网络结构给我看一下吗，我试着转一下

链接：https://pan.baidu.com/s/1CILcq0OidAt5A92aiSv56w 
提取码：dlql 
这是百度云链接，感谢感谢~

**Comment by YukiNagato** [comment]
测试过了，可以转换

**Comment by 1976277169** [comment]
> 测试过了，可以转换

好的，谢谢~

**Comment by cherishtttz** [comment]
@YukiNagato 
你好，请问你转SSD的时候，后面的transpose, slice, exp, sub, div这些层是自己添加的吗？能否请教一下怎么写这几个函数呢？

**Comment by yokings** [comment]
I have the same problem

**Comment by xinxin12345** [comment]
@cherishtttz 
您好，请问transpose, slice, exp, sub, div这些层您最后怎么处理的呢

**Comment by cherishtttz** [comment]
> @cherishtttz
> 您好，请问transpose, slice, exp, sub, div这些层您最后怎么处理的呢

transpose和split分别对应caffe里面的permute.cpp和slice.cpp哦，可以去看下源文件，然后对照其他的转换函数写一下，剩下那些操作你在生成onnx后，用onnxsim简化一下就没了，参考https://github.com/daquexian/onnx-simplifier
